# Generated by Django 4.2.1 on 2023-05-21 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_modificacion',
        ),
    ]
