# Generated by Django 4.2.1 on 2023-06-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='stripe_card_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token de tarjeta de Stripe'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de cliente de Stripe'),
        ),
    ]
