# Generated by Django 4.2.1 on 2023-06-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_apellido_customuser_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='direccion',
            field=models.CharField(default='Sin dirección', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dni',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
