# Generated by Django 4.2.1 on 2023-06-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_direccion_alter_customuser_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='direccion',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
