# Generated by Django 4.2.1 on 2023-05-17 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=50)),
                ('altura', models.CharField(max_length=5)),
                ('piso', models.CharField(blank=True, max_length=2, null=True)),
                ('departamento', models.CharField(blank=True, max_length=1, null=True)),
                ('cod_postal', models.CharField(max_length=4)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=150)),
                ('contrasena', models.CharField(max_length=15)),
                ('dni', models.CharField(max_length=8)),
                ('direccion_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='TarjetaDePago',
            fields=[
                ('id_tarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_titular', models.CharField(max_length=50)),
                ('apellido_titular', models.CharField(max_length=50)),
                ('dni_titular', models.CharField(max_length=8)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('numero_tarjeta', models.CharField(max_length=18)),
                ('codigo_seguridad', models.CharField(max_length=4)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='direccion',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
    ]
